---
ports:
  dns: 192.168.1.84:53
  http: 192.168.1.84:4000

bootstrapDns:
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query

upstreams:
  groups:
    default:
      - https://1.1.1.1/dns-query
      - https://1.0.0.1/dns-query
    river*:
      - https://1.1.1.3/dns-query
      - https://1.0.0.3/dns-query

conditional:
  fallbackUpstream: false
  mapping:
    # Forward to router
    168.192.in-addr.arpa: 192.168.1.1
    internal: 192.168.1.1
    # Forward to bind
    devbu.io: 192.168.1.84:5353
    turbo.ac: 192.168.1.84:5353

clientLookup:
  upstream: 192.168.1.1

connectIPVersion: v4

caching:
  minTime: 15m
  prefetching: true
  cacheTimeNegative: -1

ecs:
  useAsClient: true

prometheus:
  enable: true
  path: /metrics

blocking:
  loading:
    downloads:
      timeout: 60s
  blackLists:
    ads:
      - https://big.oisd.nl/domainswild
      - |
        *.androidtvchannels-pa.googleapis.com
        *.androidtvwatsonfe-pa.googleapis.com
  whiteLists:
    ads:
      - |
        *.amazonaws.com
  clientGroupsBlock:
    default:
      - ads
