services:
  dnsdist:
    # image: docker.io/powerdns/dnsdist-19:1.9.3 # amd64
    image: docker.io/kometchtech/dnsdist:1.9.3 # arm64
    container_name: dnsdist
    environment:
      - TZ=America/New_York
    network_mode: host
    # ports:
    #   - 53004:53004/tcp
    #   - 53004:53004/udp
    volumes:
      - ./dnsdist/config/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
    depends_on:
      - bind9
      - blocky
    restart: unless-stopped

  blocky:
    image: ghcr.io/0xerr0r/blocky:v0.23
    container_name: blocky
    environment:
      - TZ=America/New_York
    network_mode: host
    # ports:
    #   - 53003:53003/tcp
    #   - 53003:53003/udp
    #   - 8083:8083/tcp
    volumes:
      - ./blocky/config/config.yaml:/app/config.yml:ro
    depends_on:
      - bind9
    restart: unless-stopped

  bind9:
    image: docker.io/ubuntu/bind9:9.18-22.04_beta
    container_name: bind9
    environment:
      - BIND9_USER=root
      - TZ=America/New_York
    network_mode: host
    # ports:
    #   - 53002:53002/tcp
    #   - 53002:53002/udp
    volumes:
      - ./bind9/config:/etc/bind:ro
      - ./bind9/cache:/var/cache/bind
    restart: unless-stopped
